### ISSUE TITLE
Práctica de Calidad (moprosoft)

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-equipo-promastergamer777#1]

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 1 Calidad (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-equipo-promastergamer777/files/12786327/Practica.1.Calidad.Federico.Victoriano.Sierra.pdf)

**Comment by Heidi-19** [comment]
[Práctica 1 Calidad - Heidi Lucy Bautista Sanjuan 7USC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-equipo-promastergamer777/files/12786405/Practica.1.Calidad.-.Heidi.Lucy.Bautista.Sanjuan.7USC.pdf)

**Comment by Gregorio012** [comment]
Califi: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
